version: '3.8'

services:
  relational-exams-db:
    image: "mysql:8.0"
    container_name: relational-exams-db
    environment:
      MYSQL_DATABASE: "exams_database"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
    ports:
      - "3306:3306"
    volumes:
      - relational-exams-db:/var/lib/mysql

volumes:
  relational-exams-db: