version: '3.8'

services:
  relational-exams-db:
    image: "mysql:8.0"
    container_name: relational-exams-db
    environment:
      MYSQL_DATABASE: "exams_database"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
    ports:
      - "3306:3306"
    volumes:
      - relational-exams-db:/var/lib/mysql

  no-relational-exams-db:
    image: mongo:latest
    container_name: no-relational-exams-db
    ports:
      - "27017:27017"
    volumes:
      - no-relational-exams-db:/data/db
    environment:
      MONGO_INITDB_DATABASE: exams_database
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

volumes:
  relational-exams-db:
  no-relational-exams-db:
